/*
  *Server-only*
  Tentative hooks:
    send verification emails?
 */
var setupUser;

Accounts.onCreateUser(function(options, user) {
  user = iHealth.callbacks.run("onCreateUser", user, options);
  return user;
});


/*
  setupUser:
    doctor: only set iHealth.doctor
    patient: only set iHealth.patient
 */

setupUser = function(user, options) {
  var userObj;
  userObj = {
    profile: options.profile || (options.profile = {})
  };
  _.extend(user, userObj);
  return user;
};

iHealth.callbacks.add("onCreateUser", setupUser);

// ---
// generated by coffee-script 1.9.2
